//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSimpleWeb
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label lblTitular;
        protected global::System.Web.UI.WebControls.Label lblSaldo;
        protected global::System.Web.UI.WebControls.DropDownList ddlOperacion;
        protected global::System.Web.UI.WebControls.TextBox txtMonto;
        protected global::System.Web.UI.WebControls.Button btnOperar;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.GridView gvHistorial;
    }
}
